package com.MessageMG.common.Model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("mage_department", "departid", MageDepartment.class);
		arp.addMapping("mage_message", "newsid", MageMessage.class);
		arp.addMapping("mage_user", "userid", MageUser.class);
	}
}

