package com.MessageMG.common.Model;

import com.MessageMG.common.basemodel.BaseMageMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MageMessage extends BaseMageMessage<MageMessage> {
	public static final MageMessage dao = new MageMessage().dao();
}
