package com.MessageMG.common.Model;

import com.MessageMG.common.basemodel.BaseMageUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MageUser extends BaseMageUser<MageUser> {
	public static final MageUser dao = new MageUser().dao();
}
