package com.MessageMG.common.Model;

import com.MessageMG.common.basemodel.BaseMageDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MageDepartment extends BaseMageDepartment<MageDepartment> {
	public static final MageDepartment dao = new MageDepartment().dao();
}
