package com.MessageMG.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMageUser<M extends BaseMageUser<M>> extends Model<M> implements IBean {

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setCnname(java.lang.String cnname) {
		set("cnname", cnname);
		return (M)this;
	}
	
	public java.lang.String getCnname() {
		return getStr("cnname");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setPower(java.lang.String power) {
		set("power", power);
		return (M)this;
	}
	
	public java.lang.String getPower() {
		return getStr("power");
	}

	public M setDepartid(java.lang.Integer departid) {
		set("departid", departid);
		return (M)this;
	}
	
	public java.lang.Integer getDepartid() {
		return getInt("departid");
	}

}
