package com.MessageMG.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMageMessage<M extends BaseMageMessage<M>> extends Model<M> implements IBean {

	public M setNewsid(java.lang.Integer newsid) {
		set("newsid", newsid);
		return (M)this;
	}
	
	public java.lang.Integer getNewsid() {
		return getInt("newsid");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setNewstime(java.util.Date newstime) {
		set("newstime", newstime);
		return (M)this;
	}
	
	public java.util.Date getNewstime() {
		return get("newstime");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}
	
	public java.lang.String getContext() {
		return getStr("context");
	}

	public M setIssuer(java.lang.String issuer) {
		set("issuer", issuer);
		return (M)this;
	}
	
	public java.lang.String getIssuer() {
		return getStr("issuer");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setClicknum(java.lang.Integer clicknum) {
		set("clicknum", clicknum);
		return (M)this;
	}
	
	public java.lang.Integer getClicknum() {
		return getInt("clicknum");
	}

	public M setTitleimg(java.lang.String titleimg) {
		set("titleimg", titleimg);
		return (M)this;
	}
	
	public java.lang.String getTitleimg() {
		return getStr("titleimg");
	}

}
