package com.MessageMG.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMageDepartment<M extends BaseMageDepartment<M>> extends Model<M> implements IBean {

	public M setDepartid(java.lang.Integer departid) {
		set("departid", departid);
		return (M)this;
	}
	
	public java.lang.Integer getDepartid() {
		return getInt("departid");
	}

	public M setDepartname(java.lang.String departname) {
		set("departname", departname);
		return (M)this;
	}
	
	public java.lang.String getDepartname() {
		return getStr("departname");
	}

}
